# Generated by Django 1.10.1 on 2016-09-24 23:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(choices=[("fund", "Funding source"), ("exp", "Expenses"), ("other", "Other")], max_length=10)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "currencies",
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valid_date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.CharField(max_length=200)),
                ("create_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["valid_date", "description"],
                "verbose_name_plural": "entries",
            },
        ),
        migrations.CreateModel(
            name="EntryCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "entry categories",
            },
        ),
        migrations.CreateModel(
            name="EntryComment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("comment", models.TextField()),
                ("creator", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.Entry")),
            ],
        ),
        migrations.CreateModel(
            name="EntryComponent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=19)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entry_components", to="expenses.Account")),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="components", to="expenses.Entry")),
            ],
            options={
                "ordering": ["amount"],
            },
        ),
        migrations.CreateModel(
            name="EntryValidation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("comments", models.TextField(blank=True, null=True)),
                ("entry_component", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.EntryComponent")),
                ("validator", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="entry",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.EntryCategory"),
        ),
        migrations.AddField(
            model_name="entry",
            name="creator",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.Currency"),
        ),
        migrations.AddField(
            model_name="account",
            name="group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.AccountGroup"),
        ),
        migrations.AddField(
            model_name="account",
            name="guardian",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
